# docker-compose.yml

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: app/Dockerfile
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
