FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY . .

# Make entrypoint.sh executable
RUN chmod +x entrypoint.sh

# Expose port 8000
EXPOSE 8000

# Start the application
ENTRYPOINT ["./entrypoint.sh"]